### ISSUE TITLE
Swagger error

### ISSUE THREAD

**Issue by br33f** [GetResponse/magento#56]
**Magento 2.4.2**
**Module version 20.5.7**

After your module is installed, **/swagger** page is not working, resulting in error:

```
Fetch error
Internal Server Error https://magento.test/rest/all/schema?services=all
```

Visiting this page provides additional information about error:
```
<response>
    <message>Notice: Undefined offset: 4 in /storage/home/www/magento-test/vendor/magento/module-webapi/Model/ServiceMetadata.php on line 223</message>
    <trace>#0 /storage/home/www/magento-test/vendor/magento/module-webapi/Model/ServiceMetadata.php(223): Magento\Framework\App\ErrorHandler->handler() #1 /storage/home/www/magento-test/generated/code/Magento/Webapi/Model/ServiceMetadata/Interceptor.php(41): Magento\Webapi\Model\ServiceMetadata->getServiceName() #2 /storage/home/www/magento-test/vendor/magento/module-webapi/Model/ServiceMetadata.php(117): Magento\Webapi\Model\ServiceMetadata\Interceptor->getServiceName() #3 /storage/home/www/magento-test/vendor/magento/module-webapi/Model/ServiceMetadata.php(166): Magento\Webapi\Model\ServiceMetadata->initServicesMetadata() #4 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Model\ServiceMetadata->getServicesConfig() #5 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Model\ServiceMetadata\Interceptor->___callParent() #6 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Model\ServiceMetadata\Interceptor->Magento\Framework\Interception\{closure}() #7 /storage/home/www/magento-test/generated/code/Magento/Webapi/Model/ServiceMetadata/Interceptor.php(23): Magento\Webapi\Model\ServiceMetadata\Interceptor->___callPlugins() #8 /storage/home/www/magento-test/vendor/magento/module-webapi/Model/Rest/Swagger/Generator.php(967): Magento\Webapi\Model\ServiceMetadata\Interceptor->getServicesConfig() #9 /storage/home/www/magento-test/vendor/magento/module-webapi/Controller/Rest/SchemaRequestProcessor.php(53): Magento\Webapi\Model\Rest\Swagger\Generator->getListOfServices() #10 /storage/home/www/magento-test/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\Webapi\Controller\Rest\SchemaRequestProcessor->process() #11 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch() #12 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent() #13 /storage/home/www/magento-test/app/code/Graycore/Cors/Response/Preflight/Rest/PreflightRequestHandler.php(53): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}() #14 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(135): Graycore\Cors\Response\Preflight\Rest\PreflightRequestHandler->aroundDispatch() #15 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}() #16 /storage/home/www/magento-test/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins() #17 /storage/home/www/magento-test/vendor/magento/framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch() #18 /storage/home/www/magento-test/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http->launch() #19 /storage/home/www/magento-test/pub/index.php(29): Magento\Framework\App\Bootstrap->run() #20 {main}</trace>
</response>
```

This happens due to incorrect **webapi.xml** configuration.
According to Magento Documentation (https://developer.adobe.com/commerce/php/tutorials/backend/create-custom-rest-api/), class defined in **<service ...>** node should be interface located in Api directory.

However your module's service classes are controllers:
`<service class="GetResponse\GetResponseIntegration\Controller\Api\ModuleController" method="switch"/>`

To back up my point, please take a look at the regex pattern present in \Magento\Webapi\Model\ServiceMetadata::getServiceName
(method that throws an error):
 `$apiClassPattern = "#^(.+?)\\\\(.+?)\\\\Api\\\\(.+?)(Interface)?$#";`

**Comment by rkarkut** [comment]
We have fixed it in version 20.5.8 (magento-module version 1.2.8)
