### ISSUE TITLE
PHP 8.1 / Magento 2.4.6 compatibility

### ISSUE THREAD

**Issue by rhoerr** [GetResponse/magento#60]
I'm seeing numerous errors from the module on PHP 8.1 and Magento 2.4.6 in developer mode.
`getresponse/magento2` version: 20.6.0

Errors include:

/checkout/cart/index/ cart view:
```
Error: Call to a member function getStoreId() on null in vendor/getresponse/magento2/CustomerData/TrackingCode/ProductView.php:30
Stack trace:
#0 generated/code/Magento/Catalog/Block/Product/View/Interceptor.php(129): GetResponse\GetResponseIntegration\CustomerData\TrackingCode\ProductView->afterToHtml(Object(Magento\Catalog\Block\Product\View\Interceptor), '')
#1 vendor/magento/framework/View/Layout.php(578): Magento\Catalog\Block\Product\View\Interceptor->toHtml()
#2 vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock('crosssell')
```

/admin/getresponse/ecommerce/index/:
```
Exception #0 (Exception): Deprecated Functionality: trim(): Passing null to parameter #1 ($string) of type string is deprecated in vendor/getresponse/share-code-plugin/src/Api/GetresponseApi.php on line 680
<pre>#1 trim() called at [vendor/getresponse/share-code-plugin/src/Api/GetresponseApi.php:680]
#2 GrShareCode\Api\GetresponseApi->prepareHeaders() called at [vendor/getresponse/share-code-plugin/src/Api/GetresponseApi.php:633]
#3 GrShareCode\Api\GetresponseApi->sendRequest() called at [vendor/getresponse/share-code-plugin/src/Api/GetresponseApi.php:312]
#4 GrShareCode\Api\GetresponseApi->fetchDataWithPagination() called at [vendor/getresponse/share-code-plugin/src/Api/GetresponseApi.php:526]
#5 GrShareCode\Api\GetresponseApi->getShops() called at [vendor/getresponse/share-code-plugin/src/Api/GetresponseApiClient.php:485]
```

/admin/getresponse/webtraffic/index/:
```
Exception #0 (Exception): Warning: Undefined array key "getresponseShopId" in vendor/getresponse/magento2/Domain/Magento/WebEventTracking.php on line 97
<pre>#1 GetResponse\GetResponseIntegration\Domain\Magento\WebEventTracking::createFromArray() called at [vendor/getresponse/magento2/Block/Admin/WebEventTracking.php:30]
#2 GetResponse\GetResponseIntegration\Block\Admin\WebEventTracking->getWebEventTracking() called at [vendor/getresponse/magento2/view/adminhtml/templates/web_traffic_tracking.phtml:8]
```

This was in quickly clicking around, so there are likely similar issues elsewhere.

Thanks

**Comment by rkarkut** [comment]
Hi Ryan, first issue is already fixed in plugin version 20.6.1.
We will see how to fix second issue soon....
Could you re-authorize in GetResponse? It should help in third error.
